### ISSUE TITLE
Fare pagina about

### ISSUE THREAD

**Issue by nelsonmau** [RicostruzioneTrasparente/catalogo-dati#1]
...con la spiega complessiva

è importante fare capire la frequenza di aggiornamento di questi dati (da valutare se e come si fa)

[da assegnare a @giuragu]

**Comment by giuragu** [comment]
Aggiunta pagina about da completare: https://ricostruzionetrasparente.github.io/catalogo-dati/about.html

**Comment by nelsonmau** [comment]
grazie @giuragu. Mi viene il dubbio che forse abbia più senso fare un'unica pagina tra about e aiuto, invece di due

cosa ne pensi?

**Comment by giuragu** [comment]
Penso che sia giusto lasciarne solo una delle due. Lascio about ed elimino aiuto. Faccio subito così da lavorare sulla prima...

**Comment by giuragu** [comment]
@nelsonmau inserito un testo in pagina about. Vorrei però fissare il footer in basso....

**Comment by nelsonmau** [comment]
about mi pare buono per il momento, grazie! :-)

**Comment by giuragu** [comment]
Aggiornata la pagina about. Con le indicazioni minime indispensabili ad oggi
