### ISSUE TITLE
la tabella è ora visibile in basso ai filtri e non più alla destra

### ISSUE THREAD

**Issue by giuragu** [RicostruzioneTrasparente/catalogo-dati#5]
@nelsonmau l'aggiunta di una colonna mi ha causato qualche problema. Per esempio la [issue 4](https://github.com/RicostruzioneTrasparente/catalogo-dati/issues/4) ed ora la [tabella](https://ricostruzionetrasparente.github.io/catalogo-dati/) mi va in basso e non più sulla destra rispetto ai filtri. Quale potrebbe essere la causa?

**Comment by nelsonmau** [comment]
a me sembra che i <div> siano formattati male.

Tutto il sistema è basato su [bootstrap](http://getbootstrap.com/) che ha un'impostazione a 12 colonne. E quindi in questo caso hai sulla sx i filtri con 3 colonne e sulla destra la tabella con 9 colonne.

Assicurati che siano in div separati

**Comment by giuragu** [comment]
Grazie Andrea.
A quanto pare non era una questione di div che  ho verificato essere ok. Ho infatti appena risolto automaticamente con la issue 4. La causa era la medesima. Chiudo quindi anche questa.
